language: csharp
mono:
  - latest

solution: Aragas.Network.sln

before_install:
  - git submodule update --init --recursive
  
install:
  - nuget restore Aragas.Network.sln
  
script:
  - xbuild /p:Configuration=Release Aragas.Network.sln
  - xbuild /p:Configuration=Debug Aragas.Network.sln

notifications:
  email:
    on_success: always
